<?php
require __DIR__.'/includes/bootstrap.php'; require_login();
$page=$_GET['page']??'dashboard';
if($page==='produtos') redirect('?page=estoque');
$_SESSION['cart']??=[];
function open_cash(): array|false { global $pdo;$s=$pdo->prepare("SELECT * FROM caixas WHERE usuario_id=? AND status='aberto' ORDER BY id DESC LIMIT 1");$s->execute([$_SESSION['user']['id']]);return $s->fetch(); }
function lookup(string $table,string $name): ?int { global $pdo;$name=trim($name);if($name==='')return null;$pdo->prepare("INSERT IGNORE INTO $table(nome) VALUES(?)")->execute([$name]);$s=$pdo->prepare("SELECT id FROM $table WHERE nome=?");$s->execute([$name]);return (int)$s->fetchColumn(); }
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$a=$_POST['action']??'';
 try{
  if($a==='product_save'){
   $barcode=trim($_POST['codigo_barras']??'')?:null;
   if($barcode){$s=$pdo->prepare('SELECT pv.id,p.nome,c.nome cor,t.nome tamanho FROM produto_variacoes pv JOIN produtos p ON p.id=pv.produto_id LEFT JOIN cores c ON c.id=pv.cor_id LEFT JOIN tamanhos t ON t.id=pv.tamanho_id WHERE pv.codigo_barras=?');$s->execute([$barcode]);if($x=$s->fetch())throw new RuntimeException("Código já cadastrado em {$x['nome']} / {$x['cor']} / {$x['tamanho']}.");}
   $cost=decimal($_POST['preco_custo']);$profit=decimal($_POST['lucro_percentual']);$price=decimal($_POST['preco_venda']);if($price<=0)$price=$cost*(1+$profit/100);
   $pdo->beginTransaction();$cat=lookup('categorias',$_POST['categoria']??'');$brand=lookup('marcas',$_POST['marca']??'');$color=lookup('cores',$_POST['cor']??'');$size=lookup('tamanhos',$_POST['tamanho']??'');
   $s=$pdo->prepare('INSERT INTO produtos(nome,categoria_id,marca_id,referencia) VALUES(?,?,?,?)');$s->execute([trim($_POST['nome']),$cat,$brand,trim($_POST['referencia']??'')?:null]);$pid=(int)$pdo->lastInsertId();
   $sku=trim($_POST['sku']??'')?:'INT'.str_pad((string)$pid,8,'0',STR_PAD_LEFT);
   $stock=decimal($_POST['estoque_inicial']);$s=$pdo->prepare('INSERT INTO produto_variacoes(produto_id,cor_id,tamanho_id,sku,codigo_barras,preco_custo,lucro_percentual,preco_venda,estoque_atual,estoque_minimo,localizacao) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$pid,$color,$size,$sku,$barcode,$cost,$profit,$price,$stock,decimal($_POST['estoque_minimo']),trim($_POST['localizacao']??'')?:null]);$vid=(int)$pdo->lastInsertId();
   if($stock!=0)$pdo->prepare("INSERT INTO estoque_movimentos(variacao_id,tipo,quantidade,saldo_anterior,saldo_posterior,custo_unitario,motivo,usuario_id) VALUES(?,'inicial',?,0,?,?,'Cadastro inicial',?)")->execute([$vid,$stock,$stock,$cost,$_SESSION['user']['id']]);
   $pdo->commit();audit('cadastrar','produtos',$pid,null,['nome'=>$_POST['nome'],'codigo'=>$barcode]);flash('success','Produto cadastrado.');redirect('?page=estoque');
  }
  if($a==='customer_save'){
   $s=$pdo->prepare('INSERT INTO clientes(nome,cpf,telefone,email,endereco,limite_credito,observacoes) VALUES(?,?,?,?,?,?,?)');$s->execute([trim($_POST['nome']),trim($_POST['cpf']??'')?:null,trim($_POST['telefone']??'')?:null,trim($_POST['email']??'')?:null,trim($_POST['endereco']??'')?:null,decimal($_POST['limite_credito']),trim($_POST['observacoes']??'')?:null]);audit('cadastrar','clientes',(int)$pdo->lastInsertId());flash('success','Cliente cadastrado.');redirect('?page=clientes');
  }
  if($a==='supplier_save'){
   $s=$pdo->prepare('INSERT INTO fornecedores(nome,documento,telefone,email,observacoes) VALUES(?,?,?,?,?)');$s->execute([trim($_POST['nome']),trim($_POST['documento']??'')?:null,trim($_POST['telefone']??'')?:null,trim($_POST['email']??'')?:null,trim($_POST['observacoes']??'')?:null]);flash('success','Fornecedor cadastrado.');redirect('?page=fornecedores');
  }
  if($a==='stock'){
   $vid=(int)$_POST['variacao_id'];$qty=decimal($_POST['quantidade']);if($qty==0)throw new RuntimeException('Quantidade inválida.');$pdo->beginTransaction();$s=$pdo->prepare('SELECT estoque_atual,preco_custo FROM produto_variacoes WHERE id=? FOR UPDATE');$s->execute([$vid]);$v=$s->fetch();$new=(float)$v['estoque_atual']+$qty;if($new<0)throw new RuntimeException('O estoque não pode ficar negativo.');$pdo->prepare('UPDATE produto_variacoes SET estoque_atual=? WHERE id=?')->execute([$new,$vid]);$pdo->prepare("INSERT INTO estoque_movimentos(variacao_id,tipo,quantidade,saldo_anterior,saldo_posterior,custo_unitario,motivo,usuario_id) VALUES(?,'ajuste',?,?,?,?,?,?)")->execute([$vid,$qty,$v['estoque_atual'],$new,$v['preco_custo'],trim($_POST['motivo']),$_SESSION['user']['id']]);$pdo->commit();flash('success','Estoque ajustado.');redirect('?page=estoque');
  }
  if($a==='cash_open'){if(open_cash())throw new RuntimeException('Você já possui um caixa aberto.');$pdo->prepare('INSERT INTO caixas(usuario_id,valor_abertura) VALUES(?,?)')->execute([$_SESSION['user']['id'],decimal($_POST['valor'])]);flash('success','Caixa aberto.');redirect('?page=caixa');}
  if($a==='cash_move'){$c=open_cash();if(!$c)throw new RuntimeException('Abra o caixa.');$type=$_POST['tipo']==='sangria'?'sangria':'suprimento';$val=abs(decimal($_POST['valor']));$pdo->prepare("INSERT INTO caixa_movimentos(caixa_id,tipo,forma,valor,descricao,usuario_id) VALUES(?,?,'dinheiro',?,?,?)")->execute([$c['id'],$type,$val,trim($_POST['descricao']),$_SESSION['user']['id']]);flash('success','Movimento registrado.');redirect('?page=caixa');}
  if($a==='cash_close'){$c=open_cash();if(!$c)throw new RuntimeException('Não existe caixa aberto.');$s=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN tipo IN('venda','recebimento','suprimento') THEN valor ELSE -valor END),0) FROM caixa_movimentos WHERE caixa_id=? AND forma='dinheiro'");$s->execute([$c['id']]);$expected=(float)$c['valor_abertura']+(float)$s->fetchColumn();$informed=decimal($_POST['valor']);$pdo->prepare("UPDATE caixas SET fechado_em=NOW(),valor_esperado=?,valor_informado=?,diferenca=?,status='fechado',observacao=? WHERE id=?")->execute([$expected,$informed,$informed-$expected,trim($_POST['observacao']??''),$c['id']]);flash('success','Caixa fechado.');redirect('?page=caixa');}
  if($a==='cart_add'){
   $code=trim($_POST['codigo']);$s=$pdo->prepare("SELECT pv.*,p.nome,c.nome cor,t.nome tamanho FROM produto_variacoes pv JOIN produtos p ON p.id=pv.produto_id LEFT JOIN cores c ON c.id=pv.cor_id LEFT JOIN tamanhos t ON t.id=pv.tamanho_id WHERE pv.ativo=1 AND p.ativo=1 AND (pv.codigo_barras=? OR pv.sku=?) LIMIT 1");$s->execute([$code,$code]);$v=$s->fetch();if(!$v)throw new RuntimeException('Código não encontrado.');$id=(int)$v['id'];$qty=($_SESSION['cart'][$id]['qty']??0)+1;if($qty>(float)$v['estoque_atual'])throw new RuntimeException('Estoque insuficiente.');$_SESSION['cart'][$id]=['id'=>$id,'desc'=>$v['nome'].' / '.($v['cor']?:'-').' / '.($v['tamanho']?:'-'),'price'=>(float)$v['preco_venda'],'cost'=>(float)$v['preco_custo'],'qty'=>$qty,'stock'=>(float)$v['estoque_atual']];redirect('?page=pdv');
  }
  if($a==='cart_clear'){$_SESSION['cart']=[];redirect('?page=pdv');}
  if($a==='cart_remove'){unset($_SESSION['cart'][(int)$_POST['id']]);redirect('?page=pdv');}
  if($a==='sale_finish'){
   $c=open_cash();if(!$c)throw new RuntimeException('Abra o caixa antes de vender.');$cart=$_SESSION['cart'];if(!$cart)throw new RuntimeException('Carrinho vazio.');$subtotal=array_sum(array_map(fn($i)=>$i['price']*$i['qty'],$cart));$discount=min(max(decimal($_POST['desconto']),0),$subtotal);$total=$subtotal-$discount;$form=$_POST['forma'];$client=(int)($_POST['cliente_id']??0)?:null;if($form==='crediario'&&!$client)throw new RuntimeException('Selecione o cliente para crediário.');
   $pdo->beginTransaction();foreach($cart as $i){$s=$pdo->prepare('SELECT estoque_atual FROM produto_variacoes WHERE id=? FOR UPDATE');$s->execute([$i['id']]);if((float)$s->fetchColumn()<$i['qty'])throw new RuntimeException('Estoque insuficiente para '.$i['desc']);}
   $number='V'.date('YmdHis').random_int(10,99);$s=$pdo->prepare('INSERT INTO vendas(numero,cliente_id,caixa_id,usuario_id,subtotal,desconto,total) VALUES(?,?,?,?,?,?,?)');$s->execute([$number,$client,$c['id'],$_SESSION['user']['id'],$subtotal,$discount,$total]);$sale=(int)$pdo->lastInsertId();$ratio=$subtotal>0?$discount/$subtotal:0;
   foreach($cart as $i){$itotal=$i['price']*$i['qty']*(1-$ratio);$pdo->prepare('INSERT INTO venda_itens(venda_id,variacao_id,descricao,quantidade,preco_unitario,custo_unitario,desconto,total) VALUES(?,?,?,?,?,?,?,?)')->execute([$sale,$i['id'],$i['desc'],$i['qty'],$i['price'],$i['cost'],$i['price']*$i['qty']*$ratio,$itotal]);$old=$i['stock'];$new=$old-$i['qty'];$pdo->prepare('UPDATE produto_variacoes SET estoque_atual=estoque_atual-? WHERE id=?')->execute([$i['qty'],$i['id']]);$pdo->prepare("INSERT INTO estoque_movimentos(variacao_id,tipo,quantidade,saldo_anterior,saldo_posterior,custo_unitario,referencia_tipo,referencia_id,usuario_id) VALUES(?,'venda',?,?,?,?, 'venda',?,?)")->execute([$i['id'],-$i['qty'],$old,$new,$i['cost'],$sale,$_SESSION['user']['id']]);}
   $parts=$form==='crediario'?max(1,(int)$_POST['parcelas']):1;$pdo->prepare('INSERT INTO venda_pagamentos(venda_id,forma,valor,parcelas) VALUES(?,?,?,?)')->execute([$sale,$form,$total,$parts]);
   if($form==='crediario'){$used=$pdo->prepare("SELECT COALESCE(SUM(valor_original-valor_pago),0) FROM crediario_parcelas WHERE cliente_id=? AND status IN('aberta','parcial')");$used->execute([$client]);$cl=$pdo->prepare('SELECT limite_credito,bloqueado FROM clientes WHERE id=? FOR UPDATE');$cl->execute([$client]);$cv=$cl->fetch();if($cv['bloqueado']||(float)$used->fetchColumn()+$total>(float)$cv['limite_credito'])throw new RuntimeException('Limite de crédito insuficiente ou cliente bloqueado.');$base=round($total/$parts,2);$first=new DateTime($_POST['primeiro_vencimento']?:date('Y-m-d'));for($n=1;$n<=$parts;$n++){$val=$n===$parts?$total-$base*($parts-1):$base;$due=(clone $first)->modify('+'.($n-1).' month')->format('Y-m-d');$pdo->prepare('INSERT INTO crediario_parcelas(venda_id,cliente_id,numero_parcela,vencimento,valor_original) VALUES(?,?,?,?,?)')->execute([$sale,$client,$n,$due,$val]);}}
   else{$pdo->prepare('INSERT INTO caixa_movimentos(caixa_id,tipo,forma,valor,referencia_tipo,referencia_id,usuario_id) VALUES(?,"venda",?,?,"venda",?,?)')->execute([$c['id'],$form,$total,$sale,$_SESSION['user']['id']]);}
   $pdo->commit();$_SESSION['cart']=[];flash('success',"Venda $number finalizada: ".money($total));redirect('?page=vendas');
  }
  if($a==='credit_receive'){$c=open_cash();if(!$c)throw new RuntimeException('Abra o caixa.');$id=(int)$_POST['parcela_id'];$val=decimal($_POST['valor']);$pdo->beginTransaction();$s=$pdo->prepare("SELECT * FROM crediario_parcelas WHERE id=? FOR UPDATE");$s->execute([$id]);$p=$s->fetch();$balance=(float)$p['valor_original']-(float)$p['valor_pago'];if($val<=0||$val>$balance)throw new RuntimeException('Valor inválido.');$new=(float)$p['valor_pago']+$val;$status=$new+0.001>=(float)$p['valor_original']?'paga':'parcial';$pdo->prepare('UPDATE crediario_parcelas SET valor_pago=?,status=?,pago_em=IF(?="paga",NOW(),NULL) WHERE id=?')->execute([$new,$status,$status,$id]);$form=$_POST['forma'];$pdo->prepare('INSERT INTO crediario_recebimentos(parcela_id,caixa_id,usuario_id,forma,valor) VALUES(?,?,?,?,?)')->execute([$id,$c['id'],$_SESSION['user']['id'],$form,$val]);$pdo->prepare('INSERT INTO caixa_movimentos(caixa_id,tipo,forma,valor,referencia_tipo,referencia_id,usuario_id) VALUES(?,"recebimento",?,?,"parcela",?,?)')->execute([$c['id'],$form,$val,$id,$_SESSION['user']['id']]);$pdo->commit();flash('success','Pagamento recebido.');redirect('?page=crediario');}
  if($a==='payable_save'){$pdo->prepare('INSERT INTO contas_pagar(descricao,categoria,valor,vencimento) VALUES(?,?,?,?)')->execute([trim($_POST['descricao']),trim($_POST['categoria']),decimal($_POST['valor']),$_POST['vencimento']]);flash('success','Conta cadastrada.');redirect('?page=financeiro');}
  if($a==='payable_pay'){$pdo->prepare("UPDATE contas_pagar SET status='paga',pago_em=CURDATE() WHERE id=?")->execute([(int)$_POST['id']]);flash('success','Conta paga.');redirect('?page=financeiro');}
  if($a==='user_save'){require_admin();$pdo->prepare('INSERT INTO usuarios(nome,usuario,senha_hash,nivel) VALUES(?,?,?,?)')->execute([trim($_POST['nome']),trim($_POST['usuario']),password_hash($_POST['senha'],PASSWORD_DEFAULT),$_POST['nivel']]);flash('success','Usuário cadastrado.');redirect('?page=usuarios');}
  if($a==='settings'){require_admin();foreach(['nome_loja','lucro_padrao','desconto_maximo_caixa','max_parcelas','multa_atraso','juros_mes','impressora_mm'] as $k)$pdo->prepare('INSERT INTO configuracoes(chave,valor) VALUES(?,?) ON DUPLICATE KEY UPDATE valor=VALUES(valor)')->execute([$k,trim($_POST[$k]??'')]);flash('success','Configurações salvas.');redirect('?page=configuracoes');}
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('danger',$e->getMessage());redirect('?page='.urlencode($page));}
}
require __DIR__.'/includes/header.php';
function titlebar(string $title,string $sub=''):void{echo '<div class="section-title"><div><h1>'.e($title).'</h1><span class="muted">'.e($sub).'</span></div></div>';}
if($page==='dashboard'){
 $m=[];foreach(['today'=>"SELECT COALESCE(SUM(total),0) FROM vendas WHERE status='finalizada' AND DATE(criado_em)=CURDATE()", 'month'=>"SELECT COALESCE(SUM(total),0) FROM vendas WHERE status='finalizada' AND YEAR(criado_em)=YEAR(CURDATE()) AND MONTH(criado_em)=MONTH(CURDATE())",'low'=>"SELECT COUNT(*) FROM produto_variacoes WHERE ativo=1 AND estoque_atual<=estoque_minimo",'late'=>"SELECT COALESCE(SUM(valor_original-valor_pago),0) FROM crediario_parcelas WHERE status IN('aberta','parcial') AND vencimento<CURDATE()"] as $k=>$q)$m[$k]=$pdo->query($q)->fetchColumn();titlebar('Visão geral','Resumo da operação');echo '<div class="grid cards">';foreach([['Vendas hoje',money($m['today'])],['Vendas no mês',money($m['month'])],['Estoque baixo',$m['low']],['Crediário vencido',money($m['late'])]] as $x)echo "<div class=card><h3>{$x[0]}</h3><div class=metric>{$x[1]}</div></div>";echo '</div>';
}elseif($page==='estoque'){
 titlebar('Estoque','Consulte saldos e faça ajustes rápidos');
 $sum=$pdo->query("SELECT COUNT(*) variacoes,COALESCE(SUM(estoque_atual),0) unidades,COALESCE(SUM(estoque_atual*preco_custo),0) valor_custo,SUM(estoque_atual<=0) zerados,SUM(estoque_atual>0 AND estoque_atual<=estoque_minimo) baixos FROM produto_variacoes WHERE ativo=1")->fetch();
 $q=trim($_GET['q']??'');$status=$_GET['status']??'todos';$where=" WHERE pv.ativo=1 AND p.ativo=1";$params=[];
 if($q!==''){$where.=" AND (p.nome LIKE ? OR pv.sku LIKE ? OR pv.codigo_barras LIKE ? OR c.nome LIKE ? OR t.nome LIKE ?)";$like='%'.$q.'%';$params=array_fill(0,5,$like);}
 if($status==='zerado')$where.=" AND pv.estoque_atual<=0";elseif($status==='baixo')$where.=" AND pv.estoque_atual>0 AND pv.estoque_atual<=pv.estoque_minimo";elseif($status==='normal')$where.=" AND pv.estoque_atual>pv.estoque_minimo";
 $s=$pdo->prepare("SELECT pv.id,p.nome,pv.sku,pv.codigo_barras,c.nome cor,t.nome tamanho,pv.estoque_atual,pv.estoque_minimo,pv.preco_custo,pv.preco_venda,pv.localizacao FROM produto_variacoes pv JOIN produtos p ON p.id=pv.produto_id LEFT JOIN cores c ON c.id=pv.cor_id LEFT JOIN tamanhos t ON t.id=pv.tamanho_id".$where." ORDER BY (pv.estoque_atual<=0) DESC,(pv.estoque_atual<=pv.estoque_minimo) DESC,p.nome,c.nome,t.ordem LIMIT 500");$s->execute($params);$vars=$s->fetchAll();?>
<div class="stock-page-actions"><button type="button" class="btn primary" data-product-open>+ Adicionar produto</button></div>
<div class="grid cards stock-cards"><div class="card"><h3>Variações</h3><div class="metric"><?=e($sum['variacoes'])?></div></div><div class="card"><h3>Peças em estoque</h3><div class="metric"><?=e(number_format((float)$sum['unidades'],0,',','.'))?></div></div><div class="card"><h3>Valor pelo custo</h3><div class="metric"><?=money($sum['valor_custo'])?></div></div><div class="card alert-card"><h3>Atenção</h3><div class="metric"><?=e((int)$sum['zerados']+(int)$sum['baixos'])?></div><small><?=e($sum['zerados'])?> zeradas · <?=e($sum['baixos'])?> baixas</small></div></div>
<div class="card stock-toolbar"><form method="get" class="row"><input type="hidden" name="page" value="estoque"><div class="grow"><label>Buscar peça, código, SKU, cor ou tamanho</label><input name="q" value="<?=e($q)?>" placeholder="Digite ou use o leitor de código de barras" autofocus></div><div><label>Situação</label><select name="status"><option value="todos">Todos</option><option value="normal" <?=$status==='normal'?'selected':''?>>Normal</option><option value="baixo" <?=$status==='baixo'?'selected':''?>>Estoque baixo</option><option value="zerado" <?=$status==='zerado'?'selected':''?>>Sem estoque</option></select></div><button class="btn primary">Filtrar</button><?php if($q!==''||$status!=='todos'):?><a class="btn ghost" href="?page=estoque">Limpar</a><?php endif?></form></div>
<div class="stock-result"><strong><?=count($vars)?> variações encontradas</strong><span class="muted">Clique em “Ajustar” somente quando precisar movimentar uma peça.</span></div>
<div class="table-wrap stock-table"><table><thead><tr><th>Peça</th><th>Código / SKU</th><th>Local</th><th class="text-right">Custo</th><th class="text-right">Venda</th><th class="text-right">Saldo</th><th>Situação</th><th></th></tr></thead><tbody><?php foreach($vars as $v):$stock=(float)$v['estoque_atual'];$min=(float)$v['estoque_minimo'];$state=$stock<=0?'Sem estoque':($stock<=$min?'Estoque baixo':'Normal');$class=$stock<=0?'stock-out':($stock<=$min?'stock-low':'stock-ok');?><tr><td><strong><?=e($v['nome'])?></strong><small><?=e(($v['cor']?:'Sem cor').' · '.($v['tamanho']?:'Sem tamanho'))?></small></td><td><span class="code"><?=e($v['codigo_barras']?:$v['sku'])?></span><small><?=e($v['codigo_barras']?$v['sku']:'Código interno')?></small></td><td><?=e($v['localizacao']?:'—')?></td><td class="text-right"><?=money($v['preco_custo'])?></td><td class="text-right"><?=money($v['preco_venda'])?></td><td class="text-right stock-number"><?=e(number_format($stock,0,',','.'))?><small>Mín. <?=e(number_format($min,0,',','.'))?></small></td><td><span class="stock-badge <?=$class?>"><?=$state?></span></td><td><button type="button" class="btn ghost stock-adjust-button" data-stock-adjust data-id="<?=$v['id']?>" data-product="<?=e($v['nome'].' / '.($v['cor']?:'Sem cor').' / '.($v['tamanho']?:'Sem tamanho'))?>" data-stock="<?=e(number_format($stock,0,',','.'))?>">Ajustar</button></td></tr><?php endforeach?><?php if(!$vars):?><tr><td colspan="8" class="empty-state">Nenhuma peça encontrada com esses filtros.</td></tr><?php endif?></tbody></table></div>
<div class="modal-backdrop" id="productCreateModal" hidden aria-hidden="true">
 <section class="modal-dialog product-modal" role="dialog" aria-modal="true" aria-labelledby="productCreateTitle">
  <header class="modal-header product-modal-header"><div class="modal-heading"><span class="modal-icon">+</span><div><span class="modal-kicker">CADASTRO DE ESTOQUE</span><h2 id="productCreateTitle">Novo produto</h2><p>Cadastre a peça e sua primeira variação.</p></div></div><button type="button" class="modal-close" data-product-close aria-label="Fechar">×</button></header>
  <form method="post" id="productCreateForm">
   <?=csrf_field()?><input type="hidden" name="action" value="product_save">
   <div class="product-modal-body">
    <section class="product-form-section"><div class="product-section-title"><span>1</span><div><strong>Identificação</strong><small>Informações principais da peça</small></div></div><div class="product-form-grid identification-grid">
     <div class="product-name-field"><label for="productName">Nome do produto <b>*</b></label><input id="productName" name="nome" placeholder="Ex.: Camiseta básica feminina" required></div>
     <div><label>Referência</label><input name="referencia" placeholder="Código do fornecedor"></div><div><label>Categoria</label><input name="categoria" placeholder="Ex.: Camisetas"></div><div><label>Marca</label><input name="marca" placeholder="Ex.: Marca própria"></div>
    </div></section>
    <section class="product-form-section"><div class="product-section-title"><span>2</span><div><strong>Variação e identificação</strong><small>Cor, tamanho e códigos desta peça</small></div></div><div class="product-form-grid variation-grid">
     <div><label>Cor</label><input name="cor" placeholder="Ex.: Preto"></div><div><label>Tamanho</label><input name="tamanho" placeholder="Ex.: M"></div>
     <div><label>SKU interno</label><input name="sku" placeholder="Gerado automaticamente"></div><div><label>Código de barras</label><input name="codigo_barras" placeholder="Leia ou digite o código" autocomplete="off"></div>
    </div></section>
    <section class="product-form-section"><div class="product-section-title"><span>3</span><div><strong>Preço e estoque</strong><small>O preço é calculado automaticamente pelo lucro</small></div></div><div class="product-form-grid commercial-grid">
     <div><label for="productCost">Preço de custo</label><div class="input-addon"><span>R$</span><input id="productCost" name="preco_custo" value="0,00" inputmode="decimal"></div></div>
     <div><label for="productProfit">Lucro</label><div class="input-addon suffix"><input id="productProfit" name="lucro_percentual" value="<?=e(app_setting('lucro_padrao','100'))?>" inputmode="decimal"><span>%</span></div></div>
     <div><label for="productPrice">Preço de venda</label><div class="input-addon"><span>R$</span><input id="productPrice" name="preco_venda" placeholder="0,00" inputmode="decimal"></div></div>
     <div><label>Estoque inicial</label><input name="estoque_inicial" value="0" inputmode="decimal"></div><div><label>Estoque mínimo</label><input name="estoque_minimo" value="0" inputmode="decimal"></div><div><label>Localização</label><input name="localizacao" placeholder="Ex.: Prateleira A2"></div>
    </div></section>
   </div>
   <footer class="modal-actions product-modal-actions"><button type="button" class="btn ghost" data-product-close>Cancelar</button><button class="btn primary">Salvar produto</button></footer>
  </form>
 </section>
</div>
<div class="modal-backdrop" id="stockAdjustModal" hidden aria-hidden="true">
 <section class="modal-dialog" role="dialog" aria-modal="true" aria-labelledby="stockAdjustTitle">
  <header class="modal-header"><div><span class="modal-kicker">MOVIMENTAÇÃO DE ESTOQUE</span><h2 id="stockAdjustTitle">Ajustar estoque</h2></div><button type="button" class="modal-close" data-modal-close aria-label="Fechar">×</button></header>
  <form method="post" id="stockAdjustForm">
   <?=csrf_field()?><input type="hidden" name="action" value="stock"><input type="hidden" name="variacao_id" id="stockVariationId">
   <div class="modal-product"><strong id="stockProductName"></strong><span>Saldo atual: <b id="stockCurrentBalance"></b></span></div>
   <label for="stockQuantity">Quantidade do movimento</label>
   <input id="stockQuantity" name="quantidade" inputmode="decimal" placeholder="+ para entrada ou - para saída" required>
   <small class="field-help">Exemplos: <b>5</b> adiciona cinco peças; <b>-2</b> retira duas.</small>
   <label for="stockReason">Motivo do ajuste</label>
   <input id="stockReason" name="motivo" placeholder="Ex.: entrada manual, perda ou conferência" maxlength="255" required>
   <footer class="modal-actions"><button type="button" class="btn ghost" data-modal-close>Cancelar</button><button class="btn primary">Confirmar ajuste</button></footer>
  </form>
 </section>
</div>
<?php $moves=$pdo->query("SELECT em.*,p.nome,c.nome cor,t.nome tamanho,u.nome usuario FROM estoque_movimentos em JOIN produto_variacoes pv ON pv.id=em.variacao_id JOIN produtos p ON p.id=pv.produto_id LEFT JOIN cores c ON c.id=pv.cor_id LEFT JOIN tamanhos t ON t.id=pv.tamanho_id LEFT JOIN usuarios u ON u.id=em.usuario_id ORDER BY em.id DESC LIMIT 40")->fetchAll();?><details class="history-panel"><summary>Ver últimas movimentações</summary><div class="table-wrap"><table><tr><th>Data</th><th>Produto</th><th>Tipo</th><th>Movimento</th><th>Novo saldo</th><th>Usuário / motivo</th></tr><?php foreach($moves as $r):?><tr><td><?=e(date('d/m/Y H:i',strtotime($r['criado_em'])))?></td><td><?=e($r['nome'].' / '.$r['cor'].' / '.$r['tamanho'])?></td><td><?=e(ucfirst($r['tipo']))?></td><td class="<?=$r['quantidade']>=0?'qty-in':'qty-out'?>"><?=$r['quantidade']>=0?'+':''?><?=e(number_format((float)$r['quantidade'],0,',','.'))?></td><td><?=e(number_format((float)$r['saldo_posterior'],0,',','.'))?></td><td><?=e(($r['usuario']?:'Sistema').' · '.($r['motivo']?:'Sem observação'))?></td></tr><?php endforeach?></table></div></details>
<?php }elseif($page==='clientes'){titlebar('Clientes','Cadastro e limite do crediário');?><div class="card"><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="customer_save"><div class="form-grid"><div><label>Nome</label><input name="nome" required></div><div><label>CPF</label><input name="cpf"></div><div><label>Telefone</label><input name="telefone"></div><div><label>E-mail</label><input name="email"></div><div><label>Limite de crédito</label><input name="limite_credito" value="0,00"></div><div><label>Endereço</label><input name="endereco"></div></div><label>Observações</label><textarea name="observacoes"></textarea><p><button class="btn primary">Cadastrar</button></p></form></div><br><?php $rows=$pdo->query("SELECT c.*,COALESCE(SUM(CASE WHEN cp.status IN('aberta','parcial') THEN cp.valor_original-cp.valor_pago ELSE 0 END),0) usado FROM clientes c LEFT JOIN crediario_parcelas cp ON cp.cliente_id=c.id GROUP BY c.id ORDER BY c.nome")->fetchAll();?><div class="table-wrap"><table><tr><th>Cliente</th><th>CPF</th><th>Telefone</th><th>Limite</th><th>Utilizado</th><th>Disponível</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['nome'])?></td><td><?=e($r['cpf'])?></td><td><?=e($r['telefone'])?></td><td><?=money($r['limite_credito'])?></td><td><?=money($r['usado'])?></td><td><?=money($r['limite_credito']-$r['usado'])?></td></tr><?php endforeach?></table></div>
<?php }elseif($page==='pdv'){titlebar('Nova venda','F2 abre o PDV');$cart=$_SESSION['cart'];$subtotal=array_sum(array_map(fn($i)=>$i['price']*$i['qty'],$cart));$clients=$pdo->query("SELECT id,nome FROM clientes WHERE bloqueado=0 ORDER BY nome")->fetchAll();?><div class="grid pdv"><section><div class="card"><form method="post" class="row"><?=csrf_field()?><input type="hidden" name="action" value="cart_add"><div class="grow"><label>Código de barras ou SKU</label><input name="codigo" autofocus autocomplete="off" required></div><button class="btn primary">Adicionar</button></form></div><br><div class="table-wrap"><table><tr><th>Item</th><th>Qtd.</th><th>Preço</th><th>Total</th><th></th></tr><?php foreach($cart as $i):?><tr><td><?=e($i['desc'])?></td><td><?=e($i['qty'])?></td><td><?=money($i['price'])?></td><td><?=money($i['price']*$i['qty'])?></td><td><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="cart_remove"><input type="hidden" name="id" value="<?=$i['id']?>"><button class="btn danger">×</button></form></td></tr><?php endforeach?></table></div></section><aside class="card"><h3>Total</h3><div class="total-box"><?=money($subtotal)?></div><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="sale_finish"><label>Cliente</label><select name="cliente_id"><option value="">Consumidor</option><?php foreach($clients as $c):?><option value="<?=$c['id']?>"><?=e($c['nome'])?></option><?php endforeach?></select><label>Desconto R$</label><input name="desconto" value="0,00"><label>Pagamento</label><select name="forma" onchange="document.getElementById('credit').style.display=this.value==='crediario'?'block':'none'"><option value="dinheiro">Dinheiro</option><option value="pix">PIX</option><option value="debito">Débito</option><option value="credito">Crédito</option><option value="crediario">Crediário</option></select><div id="credit" style="display:none"><label>Parcelas</label><input type="number" name="parcelas" min="1" max="<?=e(app_setting('max_parcelas',6))?>" value="1"><label>Primeiro vencimento</label><input type="date" name="primeiro_vencimento" value="<?=date('Y-m-d',strtotime('+30 days'))?>"></div><p><button class="btn primary block">Finalizar venda</button></p></form><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="cart_clear"><button class="btn ghost block">Limpar</button></form></aside></div>
<?php }elseif($page==='caixa'){titlebar('Caixa','Abertura, sangria, suprimento e fechamento');$c=open_cash();if(!$c):?><div class="card"><h2>Caixa fechado</h2><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="cash_open"><label>Valor inicial</label><input name="valor" value="0,00"><p><button class="btn primary">Abrir caixa</button></p></form></div><?php else:$s=$pdo->prepare("SELECT forma,SUM(CASE WHEN tipo IN('venda','recebimento','suprimento') THEN valor ELSE -valor END) total FROM caixa_movimentos WHERE caixa_id=? GROUP BY forma");$s->execute([$c['id']]);?><div class="grid cards"><div class="card"><h3>Abertura</h3><div class="metric"><?=money($c['valor_abertura'])?></div></div><?php foreach($s as $x):?><div class="card"><h3><?=e(ucfirst($x['forma']))?></h3><div class="metric"><?=money($x['total'])?></div></div><?php endforeach?></div><br><div class="card"><form method="post" class="row"><?=csrf_field()?><input type="hidden" name="action" value="cash_move"><div><label>Tipo</label><select name="tipo"><option>suprimento</option><option>sangria</option></select></div><div><label>Valor</label><input name="valor" required></div><div class="grow"><label>Descrição</label><input name="descricao" required></div><button class="btn primary">Registrar</button></form><hr><form method="post" class="row"><?=csrf_field()?><input type="hidden" name="action" value="cash_close"><div><label>Dinheiro contado</label><input name="valor" required></div><div class="grow"><label>Observação</label><input name="observacao"></div><button class="btn danger" data-confirm="Fechar o caixa?">Fechar caixa</button></form></div><?php endif;
}elseif($page==='crediario'){titlebar('Crediário','Parcelas simples e recebimentos');$rows=$pdo->query("SELECT cp.*,c.nome,v.numero,(cp.valor_original-cp.valor_pago) saldo FROM crediario_parcelas cp JOIN clientes c ON c.id=cp.cliente_id JOIN vendas v ON v.id=cp.venda_id WHERE cp.status IN('aberta','parcial') ORDER BY cp.vencimento")->fetchAll();?><div class="table-wrap"><table><tr><th>Vencimento</th><th>Cliente</th><th>Venda/parcela</th><th>Original</th><th>Saldo</th><th>Receber</th></tr><?php foreach($rows as $r):?><tr><td><span class="badge <?=$r['vencimento']<date('Y-m-d')?'danger':''?>"><?=e(date('d/m/Y',strtotime($r['vencimento'])))?></span></td><td><?=e($r['nome'])?></td><td><?=e($r['numero'].' / '.$r['numero_parcela'])?></td><td><?=money($r['valor_original'])?></td><td><?=money($r['saldo'])?></td><td><form method="post" class="row"><?=csrf_field()?><input type="hidden" name="action" value="credit_receive"><input type="hidden" name="parcela_id" value="<?=$r['id']?>"><input name="valor" value="<?=number_format($r['saldo'],2,',','.')?>" style="width:100px"><select name="forma" style="width:110px"><option>dinheiro</option><option>pix</option><option>debito</option><option>credito</option></select><button class="btn primary">Receber</button></form></td></tr><?php endforeach?></table></div>
<?php }elseif($page==='fornecedores'){titlebar('Fornecedores');?><div class="card"><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="supplier_save"><div class="form-grid"><div><label>Nome</label><input name="nome" required></div><div><label>CNPJ/CPF</label><input name="documento"></div><div><label>Telefone</label><input name="telefone"></div><div><label>E-mail</label><input name="email"></div><div><label>Observações</label><input name="observacoes"></div></div><p><button class="btn primary">Cadastrar</button></p></form></div><br><?php $rows=$pdo->query('SELECT * FROM fornecedores ORDER BY nome')->fetchAll();?><div class="table-wrap"><table><tr><th>Nome</th><th>Documento</th><th>Telefone</th><th>E-mail</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['nome'])?></td><td><?=e($r['documento'])?></td><td><?=e($r['telefone'])?></td><td><?=e($r['email'])?></td></tr><?php endforeach?></table></div>
<?php }elseif($page==='financeiro'){titlebar('Financeiro','Contas a pagar');?><div class="card"><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="payable_save"><div><label>Descrição</label><input name="descricao" required></div><div><label>Categoria</label><input name="categoria"></div><div><label>Valor</label><input name="valor" required></div><div><label>Vencimento</label><input type="date" name="vencimento" required></div><div><button class="btn primary">Cadastrar conta</button></div></form></div><br><?php $rows=$pdo->query("SELECT * FROM contas_pagar WHERE status!='cancelada' ORDER BY status,vencimento")->fetchAll();?><div class="table-wrap"><table><tr><th>Vencimento</th><th>Descrição</th><th>Categoria</th><th>Valor</th><th>Status</th><th></th></tr><?php foreach($rows as $r):?><tr><td><?=e(date('d/m/Y',strtotime($r['vencimento'])))?></td><td><?=e($r['descricao'])?></td><td><?=e($r['categoria'])?></td><td><?=money($r['valor'])?></td><td><?=e($r['status'])?></td><td><?php if($r['status']==='aberta'):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="payable_pay"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn primary">Pagar</button></form><?php endif?></td></tr><?php endforeach?></table></div>
<?php }elseif($page==='vendas'){titlebar('Vendas');$rows=$pdo->query("SELECT v.*,c.nome cliente,u.nome usuario FROM vendas v LEFT JOIN clientes c ON c.id=v.cliente_id JOIN usuarios u ON u.id=v.usuario_id ORDER BY v.id DESC LIMIT 200")->fetchAll();?><div class="table-wrap"><table><tr><th>Número</th><th>Data</th><th>Cliente</th><th>Usuário</th><th>Total</th><th>Status</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['numero'])?></td><td><?=e(date('d/m/Y H:i',strtotime($r['criado_em'])))?></td><td><?=e($r['cliente']?:'Consumidor')?></td><td><?=e($r['usuario'])?></td><td><?=money($r['total'])?></td><td><?=e($r['status'])?></td></tr><?php endforeach?></table></div>
<?php }elseif($page==='relatorios'){titlebar('Relatórios');$rows=$pdo->query("SELECT p.nome,c.nome cor,t.nome tamanho,SUM(vi.quantidade) qtd,SUM(vi.total) total,SUM((vi.preco_unitario-vi.custo_unitario)*vi.quantidade-vi.desconto) lucro FROM venda_itens vi JOIN vendas v ON v.id=vi.venda_id JOIN produto_variacoes pv ON pv.id=vi.variacao_id JOIN produtos p ON p.id=pv.produto_id LEFT JOIN cores c ON c.id=pv.cor_id LEFT JOIN tamanhos t ON t.id=pv.tamanho_id WHERE v.status='finalizada' GROUP BY pv.id ORDER BY total DESC")->fetchAll();?><div class="table-wrap"><table><tr><th>Produto</th><th>Variação</th><th>Qtd.</th><th>Faturamento</th><th>Lucro bruto</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['nome'])?></td><td><?=e($r['cor'].' / '.$r['tamanho'])?></td><td><?=e($r['qtd'])?></td><td><?=money($r['total'])?></td><td><?=money($r['lucro'])?></td></tr><?php endforeach?></table></div>
<?php }elseif($page==='usuarios'){require_admin();titlebar('Usuários');?><div class="card"><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="user_save"><div><label>Nome</label><input name="nome" required></div><div><label>Usuário</label><input name="usuario" required></div><div><label>Senha</label><input type="password" name="senha" minlength="8" required></div><div><label>Nível</label><select name="nivel"><option value="caixa">Caixa</option><option value="estoque">Estoque</option><option value="admin">Administrador</option></select></div><div><button class="btn primary">Cadastrar</button></div></form></div><br><?php $rows=$pdo->query('SELECT nome,usuario,nivel,ativo,ultimo_acesso FROM usuarios ORDER BY nome')->fetchAll();?><div class="table-wrap"><table><tr><th>Nome</th><th>Usuário</th><th>Nível</th><th>Ativo</th><th>Último acesso</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['nome'])?></td><td><?=e($r['usuario'])?></td><td><?=e($r['nivel'])?></td><td><?=$r['ativo']?'Sim':'Não'?></td><td><?=e($r['ultimo_acesso']??'-')?></td></tr><?php endforeach?></table></div>
<?php }elseif($page==='configuracoes'){require_admin();titlebar('Configurações');?><div class="card"><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="settings"><div class="form-grid"><?php foreach(['nome_loja'=>'Nome da loja','lucro_padrao'=>'Lucro padrão (%)','desconto_maximo_caixa'=>'Desconto máximo (%)','max_parcelas'=>'Máximo de parcelas','multa_atraso'=>'Multa (%)','juros_mes'=>'Juros ao mês (%)','impressora_mm'=>'Impressora (mm)'] as $k=>$label):?><div><label><?=e($label)?></label><input name="<?=$k?>" value="<?=e(app_setting($k,''))?>"></div><?php endforeach?></div><p><button class="btn primary">Salvar configurações</button></p></form></div>
<?php }else{http_response_code(404);titlebar('Página não encontrada');}
require __DIR__.'/includes/footer.php';
