SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS usuarios (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nome VARCHAR(120) NOT NULL, usuario VARCHAR(60) NOT NULL UNIQUE, senha_hash VARCHAR(255) NOT NULL,
 nivel ENUM('admin','caixa','estoque') NOT NULL DEFAULT 'caixa', ativo TINYINT(1) NOT NULL DEFAULT 1,
 ultimo_acesso DATETIME NULL, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 atualizado_em DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS configuracoes (
 chave VARCHAR(80) PRIMARY KEY, valor TEXT NULL, atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT IGNORE INTO configuracoes(chave,valor) VALUES
('nome_loja','Loja de Roupas'),('lucro_padrao','100'),('desconto_maximo_caixa','10'),
('max_parcelas','6'),('multa_atraso','0'),('juros_mes','0'),('estoque_negativo','0'),('impressora_mm','80');
CREATE TABLE IF NOT EXISTS categorias (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(100) NOT NULL UNIQUE,ativo TINYINT(1) DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS marcas (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(100) NOT NULL UNIQUE,ativo TINYINT(1) DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS cores (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(60) NOT NULL UNIQUE,hex VARCHAR(7) NULL,ativo TINYINT(1) DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS tamanhos (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(30) NOT NULL UNIQUE,ordem INT DEFAULT 0,ativo TINYINT(1) DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT IGNORE INTO tamanhos(nome,ordem) VALUES ('PP',1),('P',2),('M',3),('G',4),('GG',5),('XGG',6),('Único',99);
CREATE TABLE IF NOT EXISTS fornecedores (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(150) NOT NULL,documento VARCHAR(20) NULL UNIQUE,
 contato VARCHAR(100) NULL,telefone VARCHAR(30) NULL,email VARCHAR(150) NULL,endereco TEXT NULL,observacoes TEXT NULL,
 ativo TINYINT(1) DEFAULT 1,criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS clientes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(150) NOT NULL,cpf VARCHAR(14) NULL UNIQUE,rg VARCHAR(30) NULL,
 nascimento DATE NULL,telefone VARCHAR(30) NULL,email VARCHAR(150) NULL,cep VARCHAR(10) NULL,endereco VARCHAR(180) NULL,
 numero VARCHAR(20) NULL,bairro VARCHAR(100) NULL,cidade VARCHAR(100) NULL,uf CHAR(2) NULL,
 limite_credito DECIMAL(12,2) NOT NULL DEFAULT 0,bloqueado TINYINT(1) DEFAULT 0,observacoes TEXT NULL,
 criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,atualizado_em DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS produtos (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(160) NOT NULL,descricao TEXT NULL,categoria_id BIGINT UNSIGNED NULL,
 marca_id BIGINT UNSIGNED NULL,fornecedor_id BIGINT UNSIGNED NULL,referencia VARCHAR(60) NULL,foto VARCHAR(255) NULL,
 ativo TINYINT(1) DEFAULT 1,criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,atualizado_em DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(categoria_id) REFERENCES categorias(id) ON DELETE SET NULL,FOREIGN KEY(marca_id) REFERENCES marcas(id) ON DELETE SET NULL,
 FOREIGN KEY(fornecedor_id) REFERENCES fornecedores(id) ON DELETE SET NULL,INDEX(nome)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS produto_variacoes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,produto_id BIGINT UNSIGNED NOT NULL,cor_id BIGINT UNSIGNED NULL,tamanho_id BIGINT UNSIGNED NULL,
 sku VARCHAR(60) NOT NULL UNIQUE,codigo_barras VARCHAR(60) NULL UNIQUE,preco_custo DECIMAL(12,2) NOT NULL DEFAULT 0,
 lucro_percentual DECIMAL(8,2) NOT NULL DEFAULT 0,preco_venda DECIMAL(12,2) NOT NULL DEFAULT 0,
 estoque_atual DECIMAL(12,3) NOT NULL DEFAULT 0,estoque_minimo DECIMAL(12,3) NOT NULL DEFAULT 0,localizacao VARCHAR(100) NULL,
 ativo TINYINT(1) DEFAULT 1,criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,atualizado_em DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(produto_id) REFERENCES produtos(id) ON DELETE CASCADE,FOREIGN KEY(cor_id) REFERENCES cores(id) ON DELETE SET NULL,
 FOREIGN KEY(tamanho_id) REFERENCES tamanhos(id) ON DELETE SET NULL,INDEX(codigo_barras),INDEX(produto_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS estoque_movimentos (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,variacao_id BIGINT UNSIGNED NOT NULL,
 tipo ENUM('inicial','entrada','venda','devolucao','troca','perda','ajuste','cancelamento') NOT NULL,
 quantidade DECIMAL(12,3) NOT NULL,saldo_anterior DECIMAL(12,3) NOT NULL,saldo_posterior DECIMAL(12,3) NOT NULL,
 custo_unitario DECIMAL(12,2) NULL,referencia_tipo VARCHAR(40) NULL,referencia_id BIGINT UNSIGNED NULL,
 motivo VARCHAR(255) NULL,usuario_id BIGINT UNSIGNED NULL,criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(variacao_id) REFERENCES produto_variacoes(id),FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,INDEX(criado_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS caixas (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,usuario_id BIGINT UNSIGNED NOT NULL,terminal VARCHAR(60) DEFAULT 'Principal',
 aberto_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,fechado_em DATETIME NULL,valor_abertura DECIMAL(12,2) NOT NULL DEFAULT 0,
 valor_esperado DECIMAL(12,2) NULL,valor_informado DECIMAL(12,2) NULL,diferenca DECIMAL(12,2) NULL,
 status ENUM('aberto','fechado') DEFAULT 'aberto',observacao TEXT NULL,FOREIGN KEY(usuario_id) REFERENCES usuarios(id),INDEX(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS caixa_movimentos (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,caixa_id BIGINT UNSIGNED NOT NULL,
 tipo ENUM('venda','recebimento','suprimento','sangria','estorno','devolucao') NOT NULL,
 forma ENUM('dinheiro','pix','debito','credito','crediario') NOT NULL,valor DECIMAL(12,2) NOT NULL,
 descricao VARCHAR(255) NULL,referencia_tipo VARCHAR(40) NULL,referencia_id BIGINT UNSIGNED NULL,
 usuario_id BIGINT UNSIGNED NULL,criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(caixa_id) REFERENCES caixas(id),FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS vendas (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,numero VARCHAR(30) NOT NULL UNIQUE,cliente_id BIGINT UNSIGNED NULL,
 caixa_id BIGINT UNSIGNED NOT NULL,usuario_id BIGINT UNSIGNED NOT NULL,subtotal DECIMAL(12,2) NOT NULL,
 desconto DECIMAL(12,2) NOT NULL DEFAULT 0,total DECIMAL(12,2) NOT NULL,status ENUM('finalizada','cancelada') DEFAULT 'finalizada',
 observacao TEXT NULL,criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,cancelado_em DATETIME NULL,
 FOREIGN KEY(cliente_id) REFERENCES clientes(id) ON DELETE SET NULL,FOREIGN KEY(caixa_id) REFERENCES caixas(id),FOREIGN KEY(usuario_id) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS venda_itens (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,venda_id BIGINT UNSIGNED NOT NULL,variacao_id BIGINT UNSIGNED NOT NULL,
 descricao VARCHAR(220) NOT NULL,quantidade DECIMAL(12,3) NOT NULL,preco_unitario DECIMAL(12,2) NOT NULL,
 custo_unitario DECIMAL(12,2) NOT NULL,desconto DECIMAL(12,2) DEFAULT 0,total DECIMAL(12,2) NOT NULL,
 FOREIGN KEY(venda_id) REFERENCES vendas(id) ON DELETE CASCADE,FOREIGN KEY(variacao_id) REFERENCES produto_variacoes(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS venda_pagamentos (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,venda_id BIGINT UNSIGNED NOT NULL,
 forma ENUM('dinheiro','pix','debito','credito','crediario') NOT NULL,valor DECIMAL(12,2) NOT NULL,parcelas INT DEFAULT 1,
 FOREIGN KEY(venda_id) REFERENCES vendas(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS crediario_parcelas (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,venda_id BIGINT UNSIGNED NOT NULL,cliente_id BIGINT UNSIGNED NOT NULL,
 numero_parcela INT NOT NULL,vencimento DATE NOT NULL,valor_original DECIMAL(12,2) NOT NULL,valor_pago DECIMAL(12,2) DEFAULT 0,
 pago_em DATETIME NULL,status ENUM('aberta','parcial','paga','cancelada') DEFAULT 'aberta',
 FOREIGN KEY(venda_id) REFERENCES vendas(id),FOREIGN KEY(cliente_id) REFERENCES clientes(id),INDEX(vencimento),INDEX(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS crediario_recebimentos (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,parcela_id BIGINT UNSIGNED NOT NULL,caixa_id BIGINT UNSIGNED NOT NULL,
 usuario_id BIGINT UNSIGNED NOT NULL,forma ENUM('dinheiro','pix','debito','credito') NOT NULL,valor DECIMAL(12,2) NOT NULL,
 recebido_em DATETIME DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(parcela_id) REFERENCES crediario_parcelas(id),
 FOREIGN KEY(caixa_id) REFERENCES caixas(id),FOREIGN KEY(usuario_id) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS contas_pagar (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,fornecedor_id BIGINT UNSIGNED NULL,descricao VARCHAR(180) NOT NULL,
 categoria VARCHAR(100) NULL,valor DECIMAL(12,2) NOT NULL,vencimento DATE NOT NULL,pago_em DATE NULL,
 forma_pagamento VARCHAR(40) NULL,status ENUM('aberta','paga','cancelada') DEFAULT 'aberta',observacoes TEXT NULL,
 criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(fornecedor_id) REFERENCES fornecedores(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS auditoria (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,usuario_id BIGINT UNSIGNED NULL,acao VARCHAR(80) NOT NULL,
 tabela VARCHAR(80) NULL,registro_id BIGINT UNSIGNED NULL,dados_anteriores JSON NULL,dados_posteriores JSON NULL,
 ip VARCHAR(45) NULL,user_agent VARCHAR(255) NULL,criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,INDEX(criado_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;